### ISSUE TITLE
the dataset about the kitti example.

### ISSUE THREAD

**Issue by ttomchy** [niosus/depth_clustering#7]
Thank you for sharing your source code .in the code you also provide the examples of the kitti ,I wonder that if you can share the kitti dataset or share the link of the kitti dataset that you use.

**Comment by niosus** [comment]
You can download any dataset from KITTI website: http://www.cvlibs.net/datasets/kitti/raw_data.php

The code will work on any dataset from there. You need the links labeled by `[synced+rectified data]`.

The issue with KITTI is that there is substantial noise in the sensor that I am unable to clear, so the results won't look as good. Also, I haven't really optimized the parameters there. I may work on this in future.
